### ISSUE TITLE
Adapter crash - adapter.objects.getObject is not a function at getObject 

### ISSUE THREAD

**Issue by realwax** [iobroker-community-adapters/ioBroker.yamaha#19]
JS-Controller 3.0.20
Node.js
v12.16.3
NPM
6.14.4

yamaha-community.0 | 2020-05-05 22:14:28.544 | info | (30559) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
yamaha-community.0 | 2020-05-05 22:14:28.543 | info | (30559) terminating
yamaha-community.0 | 2020-05-05 22:14:28.039 | error | (30559) TypeError: adapter.objects.getObject is not a function at getObject (/opt/iobroker/node_modules/soef/soef.js:492:28) at setObjectNotExists (/opt/iobroker/node_modules/soef/soef.js:501:
yamaha-community.0 | 2020-05-05 22:14:27.997 | error | (30559) uncaught exception: adapter.objects.getObject is not a function

**Comment by Apollon77** [comment]
Which adpter version= Try Github version please

**Comment by realwax** [comment]
Sorry for the late reply. I am using the github version

2020-08-02 14:36:13.631  - [32minfo[39m: yamaha-community.0 (6328) Terminated (NO_ERROR): Without reason
2020-08-02 14:36:14.374  - [32minfo[39m: host.iobrokerQNAP instance system.adapter.yamaha-community.0 terminated with code 0 (NO_ERROR)
2020-08-02 14:36:14.374  - [32minfo[39m: host.iobrokerQNAP Restart adapter system.adapter.yamaha-community.0 because enabled
2020-08-02 14:36:44.416  - [32minfo[39m: host.iobrokerQNAP instance system.adapter.yamaha-community.0 started with pid 6580
2020-08-02 14:36:45.865  - [32minfo[39m: yamaha-community.0 (6580) starting. Version 0.3.19 in /opt/iobroker/node_modules/iobroker.yamaha-community, node: v12.16.3, js-controller: 3.1.6
2020-08-02 14:36:56.734  - [31merror[39m: yamaha-community.0 (6580) uncaught exception: adapter.objects.getObject is not a function
2020-08-02 14:36:56.736  - [31merror[39m: yamaha-community.0 (6580) TypeError: adapter.objects.getObject is not a function
    at getObject (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:492:28)
    at setObjectNotExists (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:501:5)
    at Devices.createObjectNotExists (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:602:9)
    at Devices.setStateEx (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:632:18)
    at /opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:698:22
    at doit (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:248:13)
    at forEachObjSync (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:251:9)
    at Devices.update (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:697:9)
    at CDevice.update (/opt/iobroker/node_modules/iobroker.yamaha-community/node_modules/soef/soef.js:1028:22)
    at Y5.y5.onData (/opt/iobroker/node_modules/iobroker.yamaha-community/main.js:591:13)
    at Socket.<anonymous> (/opt/iobroker/node_modules/y5/y5.js:60:14)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
2020-08-02 14:36:57.241  - [32minfo[39m: yamaha-community.0 (6580) terminating

**Comment by Apollon77** [comment]
Please update jscontroller to a stable version
